USE `tech_db`;

CREATE TABLE IF NOT EXISTS `cms_collections` (
  `collection_id` varchar(50) NOT NULL,
  `slug` varchar(150) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `page_type` enum('HOME','CATEGORY','BRAND','CAMPAIGN','CUSTOM') NOT NULL DEFAULT 'CATEGORY',
  `category_id` varchar(50) DEFAULT NULL,
  `brand_id` varchar(50) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `sort_order` int NOT NULL DEFAULT '0',
  `metadata` json DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`collection_id`),
  UNIQUE KEY `uq_cms_collections_slug` (`slug`),
  KEY `idx_cms_collections_page_type` (`page_type`),
  KEY `idx_cms_collections_category` (`category_id`),
  KEY `idx_cms_collections_brand` (`brand_id`),
  KEY `idx_cms_collections_active_sort` (`is_active`,`sort_order`),
  CONSTRAINT `fk_cms_collections_category` FOREIGN KEY (`category_id`) REFERENCES `categories` (`category_id`) ON DELETE SET NULL,
  CONSTRAINT `fk_cms_collections_brand` FOREIGN KEY (`brand_id`) REFERENCES `brands` (`brand_id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `cms_sections` (
  `section_id` varchar(50) NOT NULL,
  `collection_id` varchar(50) NOT NULL,
  `section_type` enum('BANNER','SHORTCUT_BUTTONS','SHORTCUT_CARDS','FEATURED_PRODUCTS','BLOG_GRID','PRODUCT_GRID') NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `subtitle` varchar(255) DEFAULT NULL,
  `background_image` varchar(500) DEFAULT NULL,
  `href` varchar(500) DEFAULT NULL,
  `sort_order` int NOT NULL DEFAULT '0',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `metadata` json DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`section_id`),
  KEY `idx_cms_sections_collection` (`collection_id`),
  KEY `idx_cms_sections_type` (`section_type`),
  KEY `idx_cms_sections_active_sort` (`collection_id`,`is_active`,`sort_order`),
  CONSTRAINT `fk_cms_sections_collection` FOREIGN KEY (`collection_id`) REFERENCES `cms_collections` (`collection_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `cms_section_items` (
  `item_id` varchar(50) NOT NULL,
  `section_id` varchar(50) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `subtitle` varchar(255) DEFAULT NULL,
  `image_url` varchar(500) DEFAULT NULL,
  `href` varchar(500) DEFAULT NULL,
  `product_id` varchar(50) DEFAULT NULL,
  `variant_id` varchar(50) DEFAULT NULL,
  `blog_id` varchar(50) DEFAULT NULL,
  `sort_order` int NOT NULL DEFAULT '0',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `metadata` json DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`item_id`),
  KEY `idx_cms_section_items_section` (`section_id`),
  KEY `idx_cms_section_items_product` (`product_id`),
  KEY `idx_cms_section_items_variant` (`variant_id`),
  KEY `idx_cms_section_items_blog` (`blog_id`),
  KEY `idx_cms_section_items_active_sort` (`section_id`,`is_active`,`sort_order`),
  CONSTRAINT `fk_cms_section_items_section` FOREIGN KEY (`section_id`) REFERENCES `cms_sections` (`section_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_cms_section_items_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`product_id`) ON DELETE SET NULL,
  CONSTRAINT `fk_cms_section_items_variant` FOREIGN KEY (`variant_id`) REFERENCES `product_variants` (`variant_id`) ON DELETE SET NULL,
  CONSTRAINT `fk_cms_section_items_blog` FOREIGN KEY (`blog_id`) REFERENCES `blog_posts` (`post_id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `cms_collection_rules` (
  `rule_id` varchar(50) NOT NULL,
  `collection_id` varchar(50) NOT NULL,
  `category_id` varchar(50) DEFAULT NULL,
  `brand_id` varchar(50) DEFAULT NULL,
  `attribute_name` varchar(100) DEFAULT NULL,
  `attribute_value` varchar(100) DEFAULT NULL,
  `keyword` varchar(255) DEFAULT NULL,
  `min_price` decimal(15,2) DEFAULT NULL,
  `max_price` decimal(15,2) DEFAULT NULL,
  `sort_by` enum('NEWEST','PRICE_ASC','PRICE_DESC','BEST_SELLING','PROMOTION') NOT NULL DEFAULT 'NEWEST',
  `limit` int NOT NULL DEFAULT '20',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `metadata` json DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`rule_id`),
  KEY `idx_cms_collection_rules_collection` (`collection_id`),
  KEY `idx_cms_collection_rules_category` (`category_id`),
  KEY `idx_cms_collection_rules_brand` (`brand_id`),
  KEY `idx_cms_collection_rules_active` (`collection_id`,`is_active`),
  CONSTRAINT `fk_cms_collection_rules_collection` FOREIGN KEY (`collection_id`) REFERENCES `cms_collections` (`collection_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_cms_collection_rules_category` FOREIGN KEY (`category_id`) REFERENCES `categories` (`category_id`) ON DELETE SET NULL,
  CONSTRAINT `fk_cms_collection_rules_brand` FOREIGN KEY (`brand_id`) REFERENCES `brands` (`brand_id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
